[package]
name = "cargo-web"
version = "0.5.3"
authors = ["Jan Bujak <j@exia.io>"]
repository = "https://github.com/koute/cargo-web"
homepage = "https://github.com/koute/cargo-web"
license = "MIT/Apache-2.0"
readme = "README.md"
description = "A Cargo subcommand for the client-side Web"
keywords = ["cargo", "subcommand", "web", "asmjs", "webasm"]
categories = ["development-tools", "development-tools::cargo-plugins", "web-programming"]

exclude = ["build-scripts/**"]

[dependencies]
clap = "2"
notify = "4"
tempdir = "0.3"
rouille = { version = "1", default-features = false }
cargo_metadata = "0.4"
ansi_term = "0.10"
reqwest = "0.8"
pbr = "1"
app_dirs = "^1.1"
libflate = "0.1"
tar = "0.4"
sha1 = "0.3"
sha2 = "0.7"
digest = "0.7"
toml = "0.4"
serde = "1"
serde_derive = "1"
serde_json = "1"
handlebars = "0.29"
unicode_categories = "0.1.1"
ordermap = "0.3"
websocket = "0.20"
regex = "0.2"
walkdir = "2"

parity-wasm = "0.19"
log = "0.4"
rustc-demangle = "0.1.5"
env_logger = "0.5.0-rc.2"

[dependencies.semver]
features = ["serde"]
version = "0.8"

[features]
development-mode = []
